---
title: "create_fieldmap"
#output: html_document
date: "2024-04-10"
editor_options: 
  chunk_output_type: console
output: 
  html_notebook: 
    fig_caption: yes
fig_width: 6 
fig_height: 4 
---

# Load Libraries
```{r}
library(dplyr)
library(purrr)
```

```{r}
# If the split rows run across a range this will not work.

### Fieldbook
path <- "fieldmaps/2024_Maize_Fieldbook.csv"

fieldbook <- read.csv(path,header = T)

# Need to know the total number of split rows
# If n_split = 0 you can you the fieldbook as the fieldmap
n_split = 1

# Must add Columns to fieldmap for split rows
# Step 1: Get number of Columns between each splitrow
betweenCol <-  max(fieldbook$Column)/(n_split+1)

# Step 2: Add 2*trunc((fieldbook$Column-1)/betweenCol) to all columns
fieldbook$Column <- fieldbook$Column + 2*trunc((fieldbook$Column-1)/betweenCol)

# Step 3: Add new rows for 
new_rows <- map_dfr(unique(fieldbook$Range), function(Range) {
  data.frame(
    Range = sprintf("%02d", rep(Range, each = n_split)),
    Column = unlist(map(1:(n_split), ~ c((.x) * betweenCol + (.x-1) * 2+1, (.x) * betweenCol + (.x-1) * 2 + 2))),
    Plot = unlist(map(1:(n_split), ~ c(paste0(90, (.x ) * betweenCol + (.x-1) * 2+1), paste0(90, (.x ) * betweenCol + (.x-1) * 2 + 2))))
  )
})

colnames(new_rows) <- c("Range", "Column", "Plot")

fieldbook$Range <- sprintf("%02d", fieldbook$Range)
fieldbook$Column <- sprintf("%02d", fieldbook$Column)
fieldbook$Plot <- sprintf("%04d", fieldbook$Plot)
new_rows$Range <- sprintf("%02s", new_rows$Range)
new_rows$Column <- sprintf("%02s", new_rows$Column)
new_rows$Plot <- sprintf("%04s", new_rows$Plot)

new_rows$Type <- "skip"

# Add the new rows to the original fieldbook
fieldmap <- bind_rows(fieldbook, new_rows)

# Replace the "book" substring with "map"
result <- stringr::str_replace(basename(path), "book", "map")
result <- paste0("./fieldmaps/",result)

# Save the fieldmap to a new CSV file
write.csv(fieldmap, result, row.names = FALSE)  

```

