---
title: "Plot GIS Data"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
# Install and load necessary packages
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, plotly, tidyverse, rmarkdown, cowplot)

# Set global chunk options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Data Loading and Preparation

```{r load}
# Define the folder path for CSV files
folder_path <- "./outputs/Maize/"
fieldbook_path <- "./fieldmaps/2024_Maize_Fieldbook.csv"

# List all CSV files in the folder
file_list <- list.files(path = folder_path, pattern = "\\.csv$", full.names = TRUE)

# Read all CSV files into a list of data frames
drone_dfs <- file_list %>%
  set_names(~ basename(.) %>% str_extract(".*_2024")) %>%
  map(read_csv)

# Combine all data frames into one, adding a 'date' column from the file names
combine_data <- bind_rows(drone_dfs, .id = "date")

# Read metadata
meta_df <- read_csv(fieldbook_path) %>%
  mutate(plot = as.integer(plot)) %>%
  select(-range, -column)

# Ensure 'plot' and 'ID' are integers in the main data
combine_data <- combine_data %>%
  mutate(plot = as.integer(plot),
         ID = as.integer(ID))

# Join metadata with the main data
combine_data <- left_join(combine_data, meta_df, by = "plot")

# Convert dates
combine_data <- combine_data %>%
  mutate(date = strftime(as.Date(date, format = "%m_%d_%Y"),"%m-%d"))
```

# Plotting the Data

```{r plotting, warning=FALSE, message=FALSE}
# Define variables for plotting
plot_vars <- c("Red_mean","Green_mean","Blue_mean","NGRDI_mean","BGI_mean","GLI_mean","BI_mean",
               "SI_mean", "VARI_mean","AreaPercentage","PlantHeight","PH.10","PH.90","PlantBiomass" )

# Boxplots for each variable
boxplots <- plot_vars %>%
  map(~ ggplot(combine_data, aes(x = date, y = .data[[.]])) +
        geom_boxplot() +
        theme_bw() +
        labs(title = paste("Boxplot of", .), x = "Date", y = .))

# Display boxplots 
# Adjust the number displayed or arrange them as needed
cowplot::plot_grid(plotlist = boxplots[1:6], ncol = 2)

# Curves using variables over time
# Note: You might have to change color and grouping depending on what you want to graph.
# For example (color = Genotype, linetype = Treatment, group = interaction(Genotype, Treatment)) 
curve_plots <- plot_vars %>%
  map(~ ggplot(combine_data, aes(x = date, y = .data[[.]], color = Accession, group = Accession)) + 
        geom_smooth(se = FALSE) +
        theme_bw() +
        theme(legend.position = "none") +
        labs(title = paste("Trend of", .), x = "Date", y = .))

# Display curve plots 
# Adjust the number displayed or arrange them as needed
cowplot::plot_grid(plotlist = curve_plots[1:6], ncol = 2)
```


